name: scere
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python
  - pandas
  - jupyterlab
  - ipywidgets
  - matplotlib
  - plotly
  - sqlite
  - nodejs
  - colour
