name: sceres
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - sqlite
  - python
  - jupyterlab
  - matplotlib
  - pandas
